### ISSUE TITLE
Code is under Copyright - license information missing

### ISSUE THREAD

**Issue by surfmuggle** [marko-js/isomorphic-ui-benchmarks#9]
While i was making my first steps with the [marko tutorial](https://markojs.com/docs/installing/)  and were about to make the first commit to github i wondered what license i should pick. 

According to https://choosealicense.com/no-license/  (a site operated by GitHub, Inc.) any repository that does not include a license defaults to exclusive copyright:

> When you make a creative work (which includes code), the work is under exclusive copyright by default.  Unless you include a license that specifies otherwise, nobody else can use, copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. 

And further down 

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. 

The [marko-starter code](https://github.com/marko-js/marko-starter) also includes no license.

To my understanding this prohibits me from pushing your code to any public repository.

**Comment by 0joshuaolson1** [comment]
I think the marko-starter issue above resolved this.

**Comment by surfmuggle** [comment]
I am not sure i understand you remark.

* [marko-starter](https://github.com/marko-js/marko-starter/tree/v2.0.3) has added a license file, which fixes [Copyright - license info missing](https://github.com/marko-js/marko-starter/issues/28)
* [marko](https://github.com/marko-js/marko) has added a **chapter License** to the readme; This is better than not having it but the [github help](https://help.github.com/articles/licensing-a-repository/) reccomends to include it (see quote below)
* This issue for the [isomorphic-ui-benchmarks](https://github.com/marko-js/isomorphic-ui-benchmarks) is still valid, since the repo has no license remark inside the readme nor a license file.

## Quote form the help page

The [github help](https://help.github.com/articles/licensing-a-repository/) about licensing a repository 

> Some projects include information about their license in their README. For example, a project's 
> README may include a note saying "This project is licensed under the terms of the MIT license."
> 
> As a best practice, we encourage you to include the license file with your project.

**Comment by 0joshuaolson1** [comment]
I don't quite understand this issue myself: it's opened here, implying that
>make the first commit to github

somehow involves this repo. The marko team and several companies clearly have no problem with using marko itself, so I don't think using related benchmark code privately is going to make you liable for lawsuits.

An official answer would be nice, though.

**Comment by mlrawlings** [comment]
The license info was in the `package.json`, but I've added a `LICENSE` file as well.
https://github.com/marko-js/isomorphic-ui-benchmarks/blob/master/package.json#L26
